import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import { SpeedInsights } from "@vercel/speed-insights/next";

import "./globals.css";

import { GeistMono } from 'geist/font/mono';

// Font files can be colocated inside of `pages`
const migha = localFont({ src: './Migha-Regular.otf', variable: '--font-migha' });

const inter = Inter({
  subsets: ["latin"],
  variable: '--font-inter'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SpeedInsights/>
      <body className={`${GeistMono.variable} ${inter.variable} ${migha.variable}`}>{children}</body>
    </html>
  );
}
